import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationTabs } from "@/components/NavigationTabs";
import { Toaster } from "@/components/ui/toaster";
import { TopNav } from "@/components/TopNav";
import { MobileNavigationTabs } from "@/components/MobileNavigationTabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<NavigationTabs />
				<MobileNavigationTabs />
				<TopNav />
				<div className="min-h-[80vh] py-6 px-[2rem] lg:px-[6rem] md:mb-[150px]">
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	);
}
