export type Plant = {
	id: number;
	name: string;
	description: string;
	image: string;
	tags: string[];
	level: number;
	hardiness: hardiness;
	exposition: exposition;
	space: number;
	rank: number;
	growingTime: number;
	growingTemperature: number;
	timeToHarvest: number;
	efficiency: number;
	nutritionalValue: number;
	density: number;
	seedingDeep: number;
	seedStorage: number;
	cropPeriod: {
		cropType: string;
		start: number;
		end: number;
	}[];
};

enum category {
	vegetable = "Légume",
	fruit = "Fruit",
	flower = "Fleur",
	littleFruit = "Petit fruit",
}

enum subType {
	root = "Légume-Racine",
	fruit = "Légume-Fruit",
	leaf = "Légume-Feuille",
	grain = "Légume-Grain",
}

enum exposition {
	sun = "Ensoleillé",
	shady = "Mi-ombre",
}

enum hardiness {
	hard = "rustique",
	medium = "bisannuelle",
	soft = "annuelle",
}

export const plants = [
	{
		id: 1,
		name: "Carotte",
		category: category.vegetable,
		subType: subType.root,
		description:
			"Une carotte est une plante herbacée qui a une tige de fleur et une tige de racine. Elle est très commune dans les jardins et les champs, et est souvent utilisée comme plante de décoration.",
		image: "/carotte.jpg",
		tags: ["Légume-racine 1", "Potager"],
		level: 2,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 5,
		rank: 10,
		growingTime: 7,
		growingTemperature: 18,
		timeToHarvest: 180,
		efficiency: 8000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 0.5,
		seedStorage: 5,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 2,
		name: "Tomate",
		category: category.vegetable,
		subType: subType.fruit,
		description:
			"La tomate fait partie des solanacées, c'est un peu la reine du potager.",
		image: "/tomate.jpg",
		tags: ["Légume-fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 70,
		rank: 60,
		growingTime: 7,
		growingTemperature: 18,
		timeToHarvest: 140,
		efficiency: 12000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 0.5,
		seedStorage: 5,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Plantation",
				start: 6,
				end: 8,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 9,
			},
		],
	},
	{
		id: 3,
		name: "Tournesol",
		category: category.flower,
		subType: null,
		description:
			"La tournesol est une plante herbacée qui a une tige de fleur et une tige de racine. Elle est très commune dans les jardins et les champs, et est souvent utilisée comme plante de décoration.",
		image: "/tournesol.jpg",
		tags: ["Fleur"],
		level: 1,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 9,
			},
		],
	},
	{
		id: 4,
		name: "Courge",
		category: category.vegetable,
		description:
			"La courgette est une plante de la famille des cucurbitactées..",
		image: "/courge.jpg",
		tags: ["Légume-racine 1", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 80,
		growingTime: 6,
		growingTemperature: 20,
		timeToHarvest: 120,
		efficiency: 20000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 2,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 5,
		name: "Ail",
		category: category.vegetable,
		description: "L'ail est très prisé..",
		image: "/ail.jpg",
		tags: ["Gousse", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 15,
		rank: 20,
		growingTime: null,
		growingTemperature: null,
		timeToHarvest: 150,
		efficiency: 2000,
		nutritionalValue: null,
		density: null,
		seedingDeep: null,
		seedStorage: null,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Plantation",
				start: 6,
				end: 8,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 9,
			},
		],
	},
	{
		id: 6,
		name: "Aubergine",
		category: category.vegetable,
		description:
			"L'aubergine est un légume très commun dans les jardins et les champs.",
		image: "/aubergine.jpg",
		tags: ["Légume-racine 1", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 80,
		growingTime: 12,
		growingTemperature: 22,
		timeToHarvest: 150,
		efficiency: 3000,
		nutritionalValue: null,
		density: null,
		seedingDeep: 0.5,
		seedStorage: 4,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 7,
		name: "Haricot",
		category: category.vegetable,
		description:
			"Une carotte est une plante herbacée qui a une tige de fleur et une tige de racine. Elle est très commune dans les jardins et les champs, et est souvent utilisée comme plante de décoration.",
		image: "/haricot.jpg",
		tags: ["Légume-grain 1", "Potager"],
		level: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 8,
		name: "Laitue",
		category: category.vegetable,
		description:
			"La laitue fait partie des solanacées, c'est un peu la reine du potager.",
		image: "/laitue.jpg",
		tags: ["Légume-feuille", "Potager"],
		level: 1,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Plantation",
				start: 6,
				end: 8,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 9,
			},
		],
	},
	{
		id: 9,
		name: "Poivron",
		category: category.vegetable,
		description:
			"Le poivron est une plante herbacée qui a une tige de fleur et une tige de racine. Elle est très commune dans les jardins et les champs, et est souvent utilisée comme plante de décoration.",
		image: "/poivron.jpg",
		tags: ["Légume-fruit", "Potager"],
		level: 1,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 9,
			},
		],
	},
	{
		id: 10,
		name: "Fève",
		category: category.vegetable,
		description: "La fève est une légumineuse riche en protéines.",
		image: "/feve.jpg",
		tags: ["Légume-grain", "Potager"],
		level: 2,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 30,
		rank: 50,
		growingTime: 8,
		growingTemperature: 15,
		timeToHarvest: 120,
		efficiency: 5000,
		nutritionalValue: 6,
		density: 1,
		seedingDeep: 2,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 11,
		name: "Petits Pois",
		category: category.vegetable,
		description:
			"Les petits pois sont des légumes très appréciés pour leur douceur.",
		image: "/pois.jpg",
		tags: ["Légume-grain", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 20,
		rank: 40,
		growingTime: 6,
		growingTemperature: 15,
		timeToHarvest: 90,
		efficiency: 3000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 12,
		name: "Épinard",
		category: category.vegetable,
		description: "L'épinard est une plante à feuilles vertes très nutritive.",
		image: "/epinard.jpg",
		tags: ["Légume-feuille", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 25,
		rank: 30,
		growingTime: 5,
		growingTemperature: 15,
		timeToHarvest: 60,
		efficiency: 4000,
		nutritionalValue: 7,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 6,
			},
		],
	},
	{
		id: 13,
		name: "Concombre",
		category: category.vegetable,
		description:
			"Le concombre est un légume rafraîchissant, idéal pour les salades.",
		image: "/concombre.jpg",
		tags: ["Légume-fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 70,
		growingTime: 10,
		growingTemperature: 20,
		timeToHarvest: 70,
		efficiency: 6000,
		nutritionalValue: 4,
		density: 1,
		seedingDeep: 1,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 14,
		name: "Mangetouts",
		category: category.vegetable,
		description: "Les mangetouts sont des pois que l'on peut manger en entier.",
		image: "/mangetouts.jpg",
		tags: ["Légume-grain", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 20,
		rank: 40,
		growingTime: 6,
		growingTemperature: 15,
		timeToHarvest: 80,
		efficiency: 3500,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 15,
		name: "Patate Douce",
		category: category.vegetable,
		description: "La patate douce est un tubercule sucré et nutritif.",
		image: "/patatedouce.jpg",
		tags: ["Légume-racine", "Potager"],
		level: 2,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 60,
		growingTime: 12,
		growingTemperature: 20,
		timeToHarvest: 150,
		efficiency: 8000,
		nutritionalValue: 8,
		density: 1,
		seedingDeep: 2,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 4,
				end: 6,
			},
			{
				cropType: "Harvest",
				start: 7,
				end: 9,
			},
		],
	},
	{
		id: 16,
		name: "Blette",
		category: category.vegetable,
		description:
			"La blette est une plante à feuilles vertes, riche en nutriments.",
		image: "/blette.jpg",
		tags: ["Légume-feuille", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 30,
		rank: 50,
		growingTime: 8,
		growingTemperature: 15,
		timeToHarvest: 90,
		efficiency: 4000,
		nutritionalValue: 6,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 17,
		name: "Betterave",
		category: category.vegetable,
		description: "La betterave est un légume-racine sucré et nutritif.",
		image: "/betterave.jpg",
		tags: ["Légume-racine", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 30,
		rank: 50,
		growingTime: 8,
		growingTemperature: 15,
		timeToHarvest: 100,
		efficiency: 5000,
		nutritionalValue: 7,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 18,
		name: "Pomme de Terre",
		category: category.vegetable,
		description:
			"La pomme de terre est un tubercule très populaire dans le monde.",
		image: "/pommedeterre.jpg",
		tags: ["Légume-racine", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 30,
		rank: 50,
		growingTime: 10,
		growingTemperature: 15,
		timeToHarvest: 120,
		efficiency: 6000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 2,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 19,
		name: "Melon",
		category: category.vegetable,
		description: "Le melon est un fruit sucré et juteux, parfait pour l'été.",
		image: "/melon.jpg",
		tags: ["Fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 70,
		growingTime: 10,
		growingTemperature: 20,
		timeToHarvest: 90,
		efficiency: 7000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 1,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 4,
				end: 6,
			},
			{
				cropType: "Harvest",
				start: 7,
				end: 9,
			},
		],
	},
	{
		id: 20,
		name: "Pastèque",
		category: category.vegetable,
		description: "La pastèque est un fruit rafraîchissant, idéal pour l'été.",
		image: "/pasteque.jpg",
		tags: ["Fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 80,
		growingTime: 12,
		growingTemperature: 22,
		timeToHarvest: 90,
		efficiency: 8000,
		nutritionalValue: 6,
		density: 1,
		seedingDeep: 1,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 4,
				end: 6,
			},
			{
				cropType: "Harvest",
				start: 7,
				end: 9,
			},
		],
	},
	{
		id: 21,
		name: "Fraise",
		category: category.vegetable,
		description: "La fraise est un fruit sucré, très apprécié en dessert.",
		image: "/fraise.jpg",
		tags: ["Fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 30,
		rank: 60,
		growingTime: 8,
		growingTemperature: 20,
		timeToHarvest: 60,
		efficiency: 5000,
		nutritionalValue: 7,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 22,
		name: "Framboise",
		category: category.vegetable,
		description: "La framboise est un fruit rouge, sucré et juteux.",
		image: "/framboise.jpg",
		tags: ["Fruit", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 30,
		rank: 60,
		growingTime: 8,
		growingTemperature: 20,
		timeToHarvest: 60,
		efficiency: 5000,
		nutritionalValue: 7,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 23,
		name: "Oignon",
		category: category.vegetable,
		description: "L'oignon est un légume aromatique, essentiel en cuisine.",
		image: "/oignon.jpg",
		tags: ["Légume-racine", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 15,
		rank: 50,
		growingTime: 10,
		growingTemperature: 15,
		timeToHarvest: 100,
		efficiency: 4000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
	{
		id: 24,
		name: "Artichaut",
		category: category.vegetable,
		description:
			"L'artichaut est un légume délicat, souvent utilisé en entrée.",
		image: "/artichaut.jpg",
		tags: ["Légume", "Potager"],
		level: 2,
		hardiness: hardiness.medium,
		exposition: exposition.sun,
		space: 100,
		rank: 70,
		growingTime: 12,
		growingTemperature: 20,
		timeToHarvest: 150,
		efficiency: 6000,
		nutritionalValue: 6,
		density: 1,
		seedingDeep: 1,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 3,
				end: 5,
			},
			{
				cropType: "Harvest",
				start: 6,
				end: 8,
			},
		],
	},
	{
		id: 25,
		name: "Maïs",
		category: category.vegetable,
		description:
			"Le maïs est une céréale très populaire, utilisée dans de nombreux plats.",
		image: "/mais.jpg",
		tags: ["Céréale", "Potager"],
		level: 1,
		hardiness: hardiness.soft,
		exposition: exposition.sun,
		space: 100,
		rank: 80,
		growingTime: 10,
		growingTemperature: 20,
		timeToHarvest: 120,
		efficiency: 7000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 2,
		seedStorage: 3,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 4,
				end: 6,
			},
			{
				cropType: "Harvest",
				start: 7,
				end: 9,
			},
		],
	},
	{
		id: 26,
		name: "Poireau",
		category: category.vegetable,
		description:
			"Le poireau est un légume aromatique, souvent utilisé dans les soupes.",
		image: "/poireau.jpg",
		tags: ["Légume-racine", "Potager"],
		level: 1,
		hardiness: hardiness.hard,
		exposition: exposition.sun,
		space: 15,
		rank: 50,
		growingTime: 10,
		growingTemperature: 15,
		timeToHarvest: 120,
		efficiency: 4000,
		nutritionalValue: 5,
		density: 1,
		seedingDeep: 1,
		seedStorage: 2,
		cropPeriod: [
			{
				cropType: "Seeding",
				start: 2,
				end: 4,
			},
			{
				cropType: "Harvest",
				start: 5,
				end: 7,
			},
		],
	},
];

// fève
// petits pois
// épinard
// concombre
// mangetouts
// patate douce
// blette
// betterave
// pomme de terre
//melon
//pastèque
//fraise
// framboise
//oignon
// artichaut
//maïs
//poireau
